// Respeti data statessa:  {"aggregateLikes": 1, "analyzedInstructions": [{"name": "", "steps": [Array]}], "cheap": false, "cookingMinutes": 480, "creditsText": "I Wash You Dry", "cuisines": [], "dairyFree": false, "diets": ["gluten free"], "dishTypes": ["sauce"], 
// "extendedIngredients": [{"aisle": "Meat", "amount": 1, "consistency": "SOLID", "id": 23557, "image": "fresh-ground-beef.jpg", "measures": [Object], "meta": [Array], "name": "ground beef", "nameClean": "95 percent lean ground beef", "original": "1 pound lean ground beef", "originalName": "lean ground beef", "unit": "pound"}, 
// {"aisle": "Meat", "amount": 2, "consistency": "SOLID", "id": 1037063, "image": "raw-pork-sausage.png", "measures": [Object], "meta": [Array], "name": "sausage links", "nameClean": "sausage links", "original": "2 hot sausage links, removed from casings", "originalName": "hot sausage links, removed from casings", "unit": ""}, 
// {"aisle": "Produce", "amount": 1, "consistency": "SOLID", "id": 11282, "image": "brown-onion.png", "measures": [Object], "meta": [Array], "name": "onion", "nameClean": "onion", "original": "1 cup diced onion", "originalName": "diced onion", "unit": "cup"}, 
// {"aisle": "Produce", "amount": 8, "consistency": "SOLID", "id": 11260, "image": "mushrooms.png", "measures": [Object], "meta": [Array], "name": "button mushrooms", "nameClean": "fresh mushrooms", "original": "8 oz package button mushrooms, diced", "originalName": "package button mushrooms, diced", "unit": "oz"}, 
// {"aisle": "Produce", "amount": 8, "consistency": "SOLID", "id": 11260, "image": "mushrooms-white.jpg", "measures": [Object], "meta": [Array], "name": "button mushrooms", "nameClean": "fresh mushrooms", "original": "8 oz package button mushrooms, diced", "originalName": "package button mushrooms, diced", "unit": "oz"}, 
// {"aisle": "Produce", "amount": 2, "consistency": "SOLID", "id": 11215, "image": "garlic.png", "measures": [Object], "meta": [Array], "name": "garlic", "nameClean": "garlic", "original": "2 cloves garlic, minced", "originalName": "garlic, minced", "unit": "cloves"}, 
// {"aisle": "Produce", "amount": 28, "consistency": "SOLID", "id": 10311693, "image": "tomatoes-canned.png", "measures": [Object], "meta": [Array], "name": "canned tomatoes", "nameClean": "petite tomatoes", "original": "28 oz can petite diced tomatoes", "originalName": "petite diced tomatoes", "unit": "oz"}, 
// {"aisle": "Canned and Jarred", "amount": 15, "consistency": "SOLID", "id": 11549, "image": "tomato-sauce-or-pasta-sauce.jpg", "measures": [Object], "meta": [Array], "name": "tomato sauce", "nameClean": "canned tomato sauce", "original": "15 oz can tomato sauce", "originalName": "tomato sauce", "unit": "oz"}, 
// {"aisle": "Pasta and Rice", "amount": 2, "consistency": "SOLID", "id": 11887, "image": "tomato-paste.jpg", "measures": [Object], "meta": [Array], "name": "tomato paste", "nameClean": "tomato paste", "original": "2 tbsp tomato paste", "originalName": "tomato paste", "unit": "tbsp"}, 
// {"aisle": "Spices and Seasonings", "amount": 1, "consistency": "SOLID", "id": 1022027, "image": "dried-herbs.png", "measures": [Object], "meta": [Array], "name": "seasoning", "nameClean": "italian seasoning", "original": "1 tbsp Italian Seasoning", "originalName": "Italian Seasoning", "unit": "tbsp"}, 
// {"aisle": "Spices and Seasonings", "amount": 1, "consistency": "SOLID", "id": 2047, "image": "salt.jpg", "measures": [Object], "meta": [Array], "name": "salt", "nameClean": "table salt", "original": "1 tsp salt", "originalName": "salt", "unit": "tsp"}, 
// {"aisle": "Spices and Seasonings", "amount": 1, "consistency": "SOLID", "id": 1002030, "image": "pepper.jpg", "measures": [Object], "meta": [Array], "name": "pepper", "nameClean": "black pepper", "original": "1 tsp black pepper", "originalName": "black pepper", "unit": "tsp"}, 
// {"aisle": "Spices and Seasonings", "amount": 1, "consistency": "SOLID", "id": 1022020, "image": "garlic-powder.png", "measures": [Object], "meta": [Array], "name": "garlic powder", "nameClean": "garlic powder", "original": "1 tsp garlic powder", "originalName": "garlic powder", "unit": "tsp"}, 
// {"aisle": "Spices and Seasonings", "amount": 3, "consistency": "SOLID", "id": 2004, "image": "bay-leaves.jpg", "measures": [Object], "meta": [Array], "name": "bay leaves", "nameClean": "bay leaves", "original": "3-4 bay leaves", "originalName": "bay leaves", "unit": ""}, 
// {"aisle": "Baking", "amount": 0.33333334, "consistency": "SOLID", "id": 1214, "image": "evaporated-milk.png", "measures": [Object], "meta": [Array], "name": "evaporated milk", "nameClean": "evaporated milk", "original": "1/3 cup heavy cream or evaporated milk", "originalName": "heavy cream or evaporated milk", "unit": "cup"}], "gaps": "no", "glutenFree": true, "healthScore": 12, "id": 1079930, "image": "https://spoonacular.com/recipeImages/1079930-556x370.jpg", "imageType": "jpg", 

// "instructions": "Instructions

// In a large skillet combine ground beef, sausage, onion, and garlic.

// Brown for 2 minutes and add mushrooms. Continue stirring and browning for an additional 5 minutes.

// Drain any fat from the skillet and transfer meat mixture to crock pot.

// Add the diced tomato, tomato sauce, tomato paste, Italian seasoning, salt, pepper and garlic powder. Stir to combine. Taste the sauce and add more salt if desired.

// Add the bay leaves and stir.

// Set to low for 6-8 hours.

// Before serving remove bay leaves and stir in the heavy cream OR evaporated milk. Enjoy!", "lowFodmap": false, "occasions": [], "originalId": null, "preparationMinutes": 15, "pricePerServing": 143.51, "readyInMinutes": 495, "servings": 8, "sourceName": "I Wash You Dry", "sourceUrl": "https://iwashyoudry.com/crock-pot-pasta-bolognese/", "spoonacularScore": 53.35212326049805, "summary": "Crock Pot Pasta Bolognese Sauce might be just the sauce you are searching for. For <b>$1.44 per serving</b>, this recipe <b>covers 17%</b> of your daily requirements of vitamins and minerals. Watching your figure? This gluten free recipe has <b>174 calories</b>, <b>17g of protein</b>, and <b>6g of fat</b> per serving. This recipe serves 8. 1 person has tried and liked this recipe. It is brought to you by I Wash You Dry. From preparation to the plate, this recipe takes about <b>8 hours and 15 minutes</b>. Head to the store and pick up bay leaves, salt, tomato sauce, and a few other things to make it today. With a spoonacular <b>score of 47%</b>, this dish is pretty good. Similar recipes are <a href=\"https://spoonacular.com/recipes/crock-pot-pasta-with-eggplant-sauce-103555\">Crock Pot Pasta With Eggplant Sauce</a>, <a href=\"https://spoonacular.com/recipes/crock-pot-meaty-pasta-sauce-543261\">Crock Pot Meaty Pasta Sauce</a>, and <a href=\"https://spoonacular.com/recipes/crock-pot-cajun-sausage-pasta-sauce-618377\">Crock Pot Cajun Sausage Pasta Sauce</a>.", "sustainable": false, "title": "Crock Pot Pasta Bolognese Sauce", "vegan": false, "vegetarian": false, "veryHealthy": false, "veryPopular": false, "weightWatcherSmartPoints": 4, "winePairing": {"pairedWines": [], "pairingText": "", "productMatches": []}}